ALTER TABLE recipes
ADD COLUMN timer SMALLINT DEFAULT 0,
ADD COLUMN kcal SMALLINT DEFAULT 0,
ADD COLUMN carbs SMALLINT DEFAULT 0,
ADD COLUMN proteins SMALLINT DEFAULT 0,
ADD COLUMN fats SMALLINT DEFAULT 0;
